# Development configuration - overrides _config.yml for local development
# This file is used when running Jekyll locally to fix path issues

# Remove baseurl for local development
baseurl: ""
url: "http://localhost:4000"

# Ensure assets are loaded correctly
sass:
  style: expanded  # Use expanded for easier debugging in development

# Override any URL-related settings
github_username: traviswillett
repository: "traviswillett/hi_ai"

# Force regeneration of all files
incremental: false